### ISSUE TITLE
Colon ":" no longer rendered correctly after update to 1.0.6.

### ISSUE THREAD

**Issue by MIvanchev** [xach/zpb-ttf#20]
I just updated to 1.0.6 to be able to render exotic symbols from awkward Unicode ranges and while this works, somehow the ":" is not being rendered anymore instead appearing as a space. Could it be that a bug introduced itself or I'm doing something completely wrong?

P.S.
Just reverted to 1.0.3 and the colon is there but not the exotic symbols.

**Comment by MIvanchev** [comment]
So, I found out it works with 1.0.5 as well so it must be something introduced between the versions.

**Comment by MIvanchev** [comment]
Hey, I further nailed it down to this commit https://github.com/xach/zpb-ttf/commit/c0f53481939bdd7a884f778b78f6d52f2b2eb759. Right before that everything works fine, but this somehow breaks the ":" and maybe other glyphs.

**Comment by xach** [comment]
ZPB-TTF doesn't do any rendering, it just fetches font and glyph info from a TrueType file. I tried fetching info for ":" from the Times New Roman TrueType file, and it was able to fetch the glyph and its contours. What font are you using? Is it a font I can try using? Are you able to get the contours (via `zpb-ttf:contours`) for the ":" glyph with that font?

**Comment by 3b** [comment]
Hmm, possibly that check is a bit too strict? I'd have expected it to show half of the glyph for the failure mode I can think of for things that worked in older versions though. Would be easier to fix with a specific font to look at, but will think about how to make the check a bit more conservative.

**Comment by MIvanchev** [comment]
Hey @xach and @3b, sorry for taking longer to answer, the fonts are https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Ubuntu/Regular/UbuntuNerdFont-Regular.ttf and BlexMono Regular from here https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/IBMPlexMono/Mono/BlexMonoNerdFont-Regular.ttf. Hope this helps to lift this mistery!

**Comment by MIvanchev** [comment]
Maybe I should also provide a bit more context: I am using clx-truetype (uses zpb-ttf) in StumpWM. I also just noticed other glyphs are affected as well, e.g. "

I also did

```
(ql:quickload "zpb-ttf")
(zpb-ttf:with-font-loader (loader "~/.local/share/fonts/ubuntunerdfont-regular.ttf")
  (zpb-ttf::contours (zpb-ttf::find-glyph #\: loader)))
```

and it gave me `#()` for 1.0.6 but it gave me the following for `c0f53481939bdd7a884f778b78f6d52f2b2eb759`:

```
#(#(#<ZPB-TTF::CONTROL-POINT 190.0,453.0*>
    #<ZPB-TTF::CONTROL-POINT 190.0,426.0> #<ZPB-TTF::CONTROL-POINT 154.0,386.0>
    #<ZPB-TTF::CONTROL-POINT 123.0,386.0*> #<ZPB-TTF::CONTROL-POINT 92.0,386.0>
    #<ZPB-TTF::CONTROL-POINT 56.0,426.0> #<ZPB-TTF::CONTROL-POINT 56.0,453.0*>
    #<ZPB-TTF::CONTROL-POINT 56.0,480.0> #<ZPB-TTF::CONTROL-POINT 92.0,520.0>
    #<ZPB-TTF::CONTROL-POINT 123.0,520.0*>
    #<ZPB-TTF::CONTROL-POINT 154.0,520.0>
    #<ZPB-TTF::CONTROL-POINT 190.0,480.0>)
  #(#<ZPB-TTF::CONTROL-POINT 190.0,54.0*> #<ZPB-TTF::CONTROL-POINT 190.0,27.0>
    #<ZPB-TTF::CONTROL-POINT 154.0,-13.0>
    #<ZPB-TTF::CONTROL-POINT 123.0,-13.0*> #<ZPB-TTF::CONTROL-POINT 92.0,-13.0>
    #<ZPB-TTF::CONTROL-POINT 56.0,27.0> #<ZPB-TTF::CONTROL-POINT 56.0,54.0*>
    #<ZPB-TTF::CONTROL-POINT 56.0,81.0> #<ZPB-TTF::CONTROL-POINT 92.0,121.0>
    #<ZPB-TTF::CONTROL-POINT 123.0,121.0*>
    #<ZPB-TTF::CONTROL-POINT 154.0,121.0> #<ZPB-TTF::CONTROL-POINT 190.0,81.0>))
```

**Comment by 3b** [comment]
Yeah, that commit was broken. It was looking at the wrong glyph index, and also rejecting legitimate use of multiple copies of same contour.

#21 seems to work for those 2 fonts and the original font with recursive compounds, though  I haven't tested it much beyond that.

**Comment by MIvanchev** [comment]
I'll try it out ASAP and let you know, thanks!

**Comment by MIvanchev** [comment]
@3b, @xach: forgot to report that this fix worked out fine! Thanks. IMO it's ok for merging.
