### ISSUE TITLE
[suggestion] add support for TTC file format

### ISSUE THREAD

**Issue by dkochmanski** [xach/zpb-ttf#3]
From wikipedia:

TrueType Collection

TrueType Collection (TTC) is an extension of TrueType format that allows combining multiple fonts into a single file, creating substantial space savings for a collection of fonts with many glyphs in common. They were first available in Chinese, Japanese, and Korean versions of Windows, and supported for all regions in Windows 2000 and later.

Mac OS included support of TTC starting with Mac OS 8.5. In Mac OS, TTC has file type ttcf.

**Comment by xach** [comment]
Sounds neat. The specification is in https://www.microsoft.com/typography/otspec/otff.htm. It looks like ttc files can contain either TrueType or Postscript font data, so even if zpb-ttf adds ttc support, it's possible that the font data inside is not supported.

**Comment by dkochmanski** [comment]
ttc support has been merged in #6.
